-- =============================================================================
-- SEED — reference/lookup data, run after migrations on `supabase db reset`.
-- The app-driven schema keeps interests/relationship goals as inline text on
-- `profiles` (no lookup tables), so there is no lookup data to seed.
-- Add test accounts/fixtures here if you want a populated local DB.
-- =============================================================================
