-- OCR provider abuse protection.
--
-- The Edge Function calls public.claim_ocr_attempt() before spending a paid
-- OCR provider request. Browser/mobile clients cannot write usage rows
-- directly; they can only claim quota for the signed-in user through this RPC.

CREATE TABLE IF NOT EXISTS public.ocr_usage_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL DEFAULT 'identity_verification',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ocr_usage_events_user_created
  ON public.ocr_usage_events(user_id, created_at DESC);

ALTER TABLE public.ocr_usage_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.ocr_usage_events FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.claim_ocr_attempt(
  p_max_attempts INTEGER DEFAULT 5,
  p_window_minutes INTEGER DEFAULT 60
)
RETURNS TABLE (
  allowed BOOLEAN,
  remaining INTEGER,
  retry_after_seconds INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_current_user UUID := auth.uid();
  v_attempt_count INTEGER := 0;
  v_oldest_attempt TIMESTAMPTZ;
BEGIN
  IF v_current_user IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;

  IF p_max_attempts IS NULL OR p_max_attempts < 1 OR p_max_attempts > 50 THEN
    RAISE EXCEPTION 'Invalid OCR quota limit' USING ERRCODE = '22023';
  END IF;

  IF p_window_minutes IS NULL OR p_window_minutes < 1 OR p_window_minutes > 1440 THEN
    RAISE EXCEPTION 'Invalid OCR quota window' USING ERRCODE = '22023';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(v_current_user::TEXT));

  SELECT
    COUNT(*)::INTEGER,
    MIN(created_at)
  INTO v_attempt_count, v_oldest_attempt
  FROM public.ocr_usage_events
  WHERE user_id = v_current_user
    AND created_at >= NOW() - make_interval(mins => p_window_minutes);

  IF v_attempt_count >= p_max_attempts THEN
    RETURN QUERY
    SELECT
      FALSE,
      0,
      GREATEST(
        1,
        CEIL(
          EXTRACT(
            EPOCH FROM (
              COALESCE(v_oldest_attempt, NOW())
              + make_interval(mins => p_window_minutes)
              - NOW()
            )
          )
        )::INTEGER
      );
    RETURN;
  END IF;

  INSERT INTO public.ocr_usage_events (user_id)
  VALUES (v_current_user);

  RETURN QUERY
  SELECT
    TRUE,
    GREATEST(0, p_max_attempts - v_attempt_count - 1),
    0;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_ocr_attempt(INTEGER, INTEGER) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_ocr_attempt(INTEGER, INTEGER) TO authenticated;
